apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shoppingify
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
      nodePort: 30000
