apiVersion: v1
kind: Service
metadata:
  name: backend-dup
  namespace: backend-duplicate
spec:
  type: ClusterIP
  selector:
    app: backend-dup
  ports:
    - protocol: TCP
      port: 3500
      targetPort: 3500
