kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3500
        protocol: TCP
      - containerPort: 30001
        hostPort: 5173
        protocol: TCP
      - containerPort: 80
        hostPort: 30002
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
