apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: shoppingify
spec:
  type: NodePort
  selector:
    app: nginx-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
